[project]
name = "prefect-examples"
version = "0.1.0"
description = "Examples of how to use Prefect"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect>=3.1.2",
    "psutil>=6.1.0",
]
