[project]
name = "prefect-examples"
version = "0.1.0"
description = "Examples of how to use Prefect"
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Code = "https://github.com/PrefectHQ/examples"
