# name: Generate and Deploy Example Docs

# on:
#   push:
#     branches: [ main ]
#     paths:
#       - '**.py'
#       - 'internal/**'
#       - '.github/workflows/docs-deploy.yml'
#   workflow_dispatch:  # Allow manual triggering

# jobs:
#   generate-and-deploy-docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout examples repo
#         uses: actions/checkout@v3
        
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
          
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r internal/requirements.txt
          
#       - name: Generate docs
#         run: python -m internal generate-docs -o temp_docs
        
#       - name: Checkout Prefect docs repo
#         uses: actions/checkout@v3
#         with:
#           repository: PrefectHQ/prefect
#           path: prefect
#           token: ${{ secrets.GH_PAT }}  # You'll need a PAT with repo scope
          
#       - name: Copy docs to Prefect repo
#         run: |
#           mkdir -p prefect/docs/v3/examples
#           cp -r temp_docs/* prefect/docs/v3/examples/
          
#       - name: Check for changes
#         id: check_changes
#         run: |
#           cd prefect
#           git status
#           if [[ -n $(git status --porcelain) ]]; then
#             echo "changes_detected=true" >> $GITHUB_OUTPUT
#           else
#             echo "changes_detected=false" >> $GITHUB_OUTPUT
#           fi
      
#       - name: Create PR
#         if: steps.check_changes.outputs.changes_detected == 'true'
#         uses: peter-evans/create-pull-request@v5
#         with:
#           path: prefect
#           token: ${{ secrets.GH_PAT }}
#           commit-message: "Update examples documentation"
#           title: "Update examples documentation"
#           body: |
#             This PR updates the example documentation based on the latest changes in the `prefect-examples` repository.
            
#             Generated automatically by the docs-deploy GitHub Action.
#           branch: update-examples-docs
#           base: main 